<a href="https://colab.research.google.com/github/thanh-huy/SIC_Excercies/blob/main/Chapt2Ex1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.__version__

'2.0.2'

In [4]:
np.array([1,3,5,7,9])

array([1, 3, 5, 7, 9])

In [5]:
arr1 = np.array([1,3,5,7,9])
type(arr1)

numpy.ndarray

In [6]:
id(arr1)

134535120853328

In [7]:
arr2 = np.array([2,4,6,8])
id(arr2)

134535121094672

In [9]:
arr3 = arr1
id(arr3)

134535120853328

In [11]:
arr3 = np.copy(arr1)
arr3

134535120588304

# Tạo mảng với tuple

In [12]:
type((1,3,5,7,9))

tuple

In [13]:
np.array((1,3,5,7,9))

array([1, 3, 5, 7, 9])

In [15]:
dict1 = type({'one':1, 'two':2, 'three':2})

In [17]:
np.array({'one':1, 'two':2, 'three':2})

array({'one': 1, 'two': 2, 'three': 2}, dtype=object)

In [19]:
type({1,1,1,2,2,3,3,3,3,4,4,5})

set

In [20]:
np.array({1,1,1,2,2,3,3,3,3,4,4,5})

array({1, 2, 3, 4, 5}, dtype=object)

# Tạo mảng với arrange

In [21]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
[i for i in np.arange(10)]

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)]

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [32]:
len10 = np.arange(10)

In [33]:
len(len10)

10

In [34]:
np.array([111,2.3,True])

array([111. ,   2.3,   1. ])

In [40]:
arr = np.array([111,2.3,'hello'], dtype='<U10')

In [41]:
type(arr)

numpy.ndarray

In [43]:
arr4 = np.array(['apple','banana','strawberry'])

In [44]:
type(arr4[0])

numpy.str_

# Hàm linspace

In [45]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [46]:
np.linspace(-10,10,20)

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [47]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [48]:
np.ones(5)

array([1., 1., 1., 1., 1.])

# Mảng nhiều chiều

In [49]:
lst1 = [[1,2,3],[4,5,6],[7,8,9]]

In [51]:
lst1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [50]:
lst1[0][0]

1

In [53]:
arr2d = np.array(lst1)

In [55]:
arr2d.ndim

2

In [56]:
arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])


In [58]:
arr3d.ndim

3

In [61]:
arr2dZeros=np.zeros((2,3))
type(arr2dZeros[0][0])

numpy.float64

In [62]:
arr2dZero2 = np.zeros((2,3),dtype='int64')

In [65]:
arr2dZero2
type(arr2dZero2[0][0])

numpy.int64

In [67]:
#Chuyển kiểu dữ liệu với astype
arr2dZero2.astype('int32')

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [68]:
arr3.size

5

In [69]:
arr3.shape

(5,)

In [70]:
arr3.ndim

1

In [ ]:
# Định nghĩa lại hình dạng của mạng reshape

In [71]:
a2 = np.arange(15)

In [74]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [75]:
a2.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [81]:
# Tạo số ngẫu nhiên random. random.randn
data = np.random.randn(2,3)

In [82]:
data

array([[-0.82431274, -0.07834605,  1.44908265],
       [ 0.22601235, -0.00380014, -0.62504501]])

In [83]:
np.mean(data)

np.float64(0.02393184484541853)

In [86]:
data2 = np.random.randn(1000,1000)

In [87]:
np.mean(data2)

np.float64(0.0005703294855559268)

In [88]:
data2

array([[ 0.40599816, -0.34795831, -1.24995541, ..., -0.83089785,
        -1.05912269,  0.4471667 ],
       [ 1.30207634,  0.16390561, -0.20406123, ...,  2.66287213,
         0.04021169,  0.9267326 ],
       [-1.17920611, -1.81808715, -0.2879465 , ..., -0.88422986,
        -0.64962165, -1.84678513],
       ...,
       [-1.98686778,  0.61290788, -0.11449477, ..., -0.2180377 ,
        -0.6781741 , -0.84882948],
       [-0.63161593, -0.14269898, -0.22255965, ..., -0.84858774,
         2.04597715, -1.00032087],
       [-0.29124603,  0.3508394 , -0.02707101, ..., -0.72578354,
         0.65675677, -0.59374198]])

# So sánh tốc độ xử lý

In [92]:
%time for i in range(1000): np.arange(1000000)*2

CPU times: user 1.28 s, sys: 0 ns, total: 1.28 s
Wall time: 1.28 s


In [93]:
%time for i in range(1000): list(range(1000000))*2

CPU times: user 42.2 s, sys: 15.3 s, total: 57.5 s
Wall time: 57.8 s


In [94]:
a = np.array([1,2,3])

In [95]:
b = np.append(a,[4,5,6])

In [96]:
b

array([1, 2, 3, 4, 5, 6])

In [97]:
a = np.array([[1,3], [2,4]])

In [110]:
a

array([[1, 3],
       [2, 4]])

In [111]:
b = np.append(a,[[5,6]],axis=0)

In [108]:
b

array([[1, 3],
       [2, 4],
       [5, 6]])

In [112]:
c = np.append(a,[[7],[7]],axis=1)

In [113]:
c

array([[1, 3, 7],
       [2, 4, 7]])

In [114]:
np.delete(a,0)

array([3, 2, 4])

In [123]:
a = np.arange(9)

In [128]:
b =a.reshape(3,3)

In [129]:
np.delete(b,1,axis=1)

array([[0, 2],
       [3, 5],
       [6, 8]])