<a href="https://colab.research.google.com/github/thanh-huy/SIC_Excercies/blob/main/Chapt2Ex1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.__version__

'2.0.2'

In [4]:
np.array([1,3,5,7,9])

array([1, 3, 5, 7, 9])

In [5]:
arr1 = np.array([1,3,5,7,9])
type(arr1)

numpy.ndarray

In [6]:
id(arr1)

134535120853328

In [7]:
arr2 = np.array([2,4,6,8])
id(arr2)

134535121094672

In [9]:
arr3 = arr1
id(arr3)

134535120853328

In [11]:
arr3 = np.copy(arr1)
arr3

134535120588304

# Tạo mảng với tuple

In [12]:
type((1,3,5,7,9))

tuple

In [13]:
np.array((1,3,5,7,9))

array([1, 3, 5, 7, 9])

In [15]:
dict1 = type({'one':1, 'two':2, 'three':2})

In [17]:
np.array({'one':1, 'two':2, 'three':2})

array({'one': 1, 'two': 2, 'three': 2}, dtype=object)

In [19]:
type({1,1,1,2,2,3,3,3,3,4,4,5})

set

In [20]:
np.array({1,1,1,2,2,3,3,3,3,4,4,5})

array({1, 2, 3, 4, 5}, dtype=object)

# Tạo mảng với arrange

In [21]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
[i for i in np.arange(10)]

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)]

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [32]:
len10 = np.arange(10)

In [33]:
len(len10)

10

In [34]:
np.array([111,2.3,True])

array([111. ,   2.3,   1. ])

In [40]:
arr = np.array([111,2.3,'hello'], dtype='<U10')

In [41]:
type(arr)

numpy.ndarray

In [43]:
arr4 = np.array(['apple','banana','strawberry'])

In [44]:
type(arr4[0])

numpy.str_

# Hàm linspace

In [45]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [46]:
np.linspace(-10,10,20)

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [47]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [48]:
np.ones(5)

array([1., 1., 1., 1., 1.])

# Mảng nhiều chiều

In [49]:
lst1 = [[1,2,3],[4,5,6],[7,8,9]]

In [51]:
lst1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [50]:
lst1[0][0]

1

In [53]:
arr2d = np.array(lst1)

In [55]:
arr2d.ndim

2

In [56]:
arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])


In [58]:
arr3d.ndim

3

In [61]:
arr2dZeros=np.zeros((2,3))
type(arr2dZeros[0][0])

numpy.float64

In [62]:
arr2dZero2 = np.zeros((2,3),dtype='int64')

In [65]:
arr2dZero2
type(arr2dZero2[0][0])

numpy.int64

In [67]:
#Chuyển kiểu dữ liệu với astype
arr2dZero2.astype('int32')

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [68]:
arr3.size

5

In [69]:
arr3.shape

(5,)

In [70]:
arr3.ndim

1

In [ ]:
# Định nghĩa lại hình dạng của mạng reshape

In [71]:
a2 = np.arange(15)

In [74]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [75]:
a2.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [81]:
# Tạo số ngẫu nhiên random. random.randn
data = np.random.randn(2,3)

In [82]:
data

array([[-0.82431274, -0.07834605,  1.44908265],
       [ 0.22601235, -0.00380014, -0.62504501]])

In [83]:
np.mean(data)

np.float64(0.02393184484541853)

In [86]:
data2 = np.random.randn(1000,1000)

In [87]:
np.mean(data2)

np.float64(0.0005703294855559268)

In [88]:
data2

array([[ 0.40599816, -0.34795831, -1.24995541, ..., -0.83089785,
        -1.05912269,  0.4471667 ],
       [ 1.30207634,  0.16390561, -0.20406123, ...,  2.66287213,
         0.04021169,  0.9267326 ],
       [-1.17920611, -1.81808715, -0.2879465 , ..., -0.88422986,
        -0.64962165, -1.84678513],
       ...,
       [-1.98686778,  0.61290788, -0.11449477, ..., -0.2180377 ,
        -0.6781741 , -0.84882948],
       [-0.63161593, -0.14269898, -0.22255965, ..., -0.84858774,
         2.04597715, -1.00032087],
       [-0.29124603,  0.3508394 , -0.02707101, ..., -0.72578354,
         0.65675677, -0.59374198]])

# So sánh tốc độ xử lý

In [92]:
%time for i in range(1000): np.arange(1000000)*2

CPU times: user 1.28 s, sys: 0 ns, total: 1.28 s
Wall time: 1.28 s


In [93]:
%time for i in range(1000): list(range(1000000))*2

CPU times: user 42.2 s, sys: 15.3 s, total: 57.5 s
Wall time: 57.8 s


In [94]:
a = np.array([1,2,3])

In [95]:
b = np.append(a,[4,5,6])

In [96]:
b

array([1, 2, 3, 4, 5, 6])

In [97]:
a = np.array([[1,3], [2,4]])

In [110]:
a

array([[1, 3],
       [2, 4]])

In [111]:
b = np.append(a,[[5,6]],axis=0)

In [108]:
b

array([[1, 3],
       [2, 4],
       [5, 6]])

In [112]:
c = np.append(a,[[7],[7]],axis=1)

In [113]:
c

array([[1, 3, 7],
       [2, 4, 7]])

In [114]:
np.delete(a,0)

array([3, 2, 4])

In [123]:
a = np.arange(9)

In [128]:
b =a.reshape(3,3)

In [129]:
np.delete(b,1,axis=1)

array([[0, 2],
       [3, 5],
       [6, 8]])

# Thống kê với numpy

In [130]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [132]:
x = np.arange(1,11)

In [134]:
print(x.sum())

55


In [135]:
x.mean()

np.float64(5.5)

In [137]:
x_mean = x.mean()

In [138]:
x-x_mean

array([-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])

In [139]:
(x-x_mean)**2

array([20.25, 12.25,  6.25,  2.25,  0.25,  0.25,  2.25,  6.25, 12.25,
       20.25])

In [140]:
dev = (x-x_mean)**2

In [141]:
dev.sum() #tổng bình phương độ lệch

np.float64(82.5)

In [142]:
#Phương sai
dev.sum()/x.size

np.float64(8.25)

In [143]:
#Phương sai
x.var()

np.float64(8.25)

In [144]:
# Độ lệch chuẩn
np.sqrt(x.var())

np.float64(2.8722813232690143)

In [145]:
x.std()

np.float64(2.8722813232690143)

In [146]:
#Tổng tích lũy
x.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [147]:
x = np.arange(1,7)

In [148]:
x

array([1, 2, 3, 4, 5, 6])

In [149]:
x.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [150]:
x.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [151]:
x.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

# Thống kê theo từng hàng và cột

In [152]:
x = x.reshape(2,3)

In [153]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [154]:
x.mean(axis=0)

array([2.5, 3.5, 4.5])

In [155]:
x.mean(axis=1)

array([2., 5.])

# Tạo số ngẫu nhiên trong numpy

In [184]:
np.random.seed(42)

In [185]:
np.random.randint(10)

6

In [189]:
# Hàm được sử dụng thường xuyên
x=np.arange(6)

In [190]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [191]:
np.exp(x)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [204]:
a = np.arange(100)

In [205]:
a.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [206]:
a.size

100

In [207]:
np.unique(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [208]:
np.median(a)

np.float64(49.5)

In [209]:
np.sum(a)

np.int64(4950)

In [210]:
np.round(np.var(a),2)

np.float64(833.25)

In [211]:
np.round(np.std(a),2)

np.float64(28.87)

In [212]:
np.max(a)

np.int64(99)

In [213]:
np.argmax(a)

np.int64(99)

In [214]:
np.min(a)

np.int64(0)

In [215]:
np.argmin(a)

np.int64(0)

In [216]:
z = np.random.randint(10,size=1000)

In [217]:
z

array([3, 7, 4, 6, 9, 2, 6, 7, 4, 3, 7, 7, 2, 5, 4, 1, 7, 5, 1, 4, 0, 9,
       5, 8, 0, 9, 2, 6, 3, 8, 2, 4, 2, 6, 4, 8, 6, 1, 3, 8, 1, 9, 8, 9,
       4, 1, 3, 6, 7, 2, 0, 3, 1, 7, 3, 1, 5, 5, 9, 3, 5, 1, 9, 1, 9, 3,
       7, 6, 8, 7, 4, 1, 4, 7, 9, 8, 8, 0, 8, 6, 8, 7, 0, 7, 7, 2, 0, 7,
       2, 2, 0, 4, 9, 6, 9, 8, 6, 8, 7, 1, 0, 6, 6, 7, 4, 2, 7, 5, 2, 0,
       2, 4, 2, 0, 4, 9, 6, 6, 8, 9, 9, 2, 6, 0, 3, 3, 4, 6, 6, 3, 6, 2,
       5, 1, 9, 8, 4, 5, 3, 9, 6, 8, 6, 0, 0, 8, 8, 3, 8, 2, 6, 5, 7, 8,
       4, 0, 2, 9, 7, 5, 7, 8, 3, 0, 0, 9, 3, 6, 1, 2, 0, 4, 0, 7, 0, 0,
       1, 1, 5, 6, 4, 0, 0, 2, 1, 4, 9, 5, 6, 3, 6, 7, 0, 5, 7, 4, 3, 1,
       5, 5, 0, 8, 5, 2, 3, 3, 2, 9, 2, 2, 3, 6, 3, 8, 0, 7, 6, 1, 7, 0,
       8, 8, 1, 6, 9, 2, 6, 9, 8, 3, 0, 1, 0, 4, 4, 6, 8, 8, 2, 2, 2, 3,
       7, 5, 7, 0, 7, 3, 0, 7, 3, 5, 7, 3, 2, 8, 2, 8, 1, 1, 1, 5, 2, 8,
       3, 0, 3, 0, 4, 3, 7, 7, 6, 2, 0, 0, 2, 5, 6, 5, 5, 5, 2, 5, 7, 1,
       4, 0, 0, 4, 2, 3, 2, 0, 0, 4, 5, 2, 8, 4, 7,

In [218]:
np.unique(z)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [219]:
set(z)

{np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)}

# Các phép toán trên ma trận

In [221]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [222]:
B = np.array([3,2,-1,0]).reshape(2,2)
B

array([[ 3,  2],
       [-1,  0]])

In [223]:
# A*B
A.dot(B)

array([[-1,  0],
       [ 3,  4]])

In [224]:
np.dot(A,B)

array([[-1,  0],
       [ 3,  4]])

In [225]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [226]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [227]:
np.linalg.det(A)

np.float64(-2.0)