<a href="https://colab.research.google.com/github/thanh-huy/SIC_Excercies/blob/main/Exam0103.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
a1 = np.array([0,10,20,30,40,50])
a1[5]

np.int64(50)

In [5]:
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [6]:
#Lấy danh sách phần tử ở vị trí 1,3,4
a1[[1,3,4]]

array([10, 30, 40])

In [8]:
#Tạo mảng 3 chiều:9 phần tử giá trị từ 10-90,
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [10]:
a2[1] # Lấy toàn bộ hàng số 1

array([40, 50, 60])

In [14]:
a2[2] = np.array([45,55,65]) #Gán hàng số 2 mảng mới
a2 #lưu ý phải kiểu numpy.array

array([[10, 20, 30],
       [40, 50, 60],
       [45, 55, 65]])

In [18]:
a2[[0,2,1],[0,1,1]] #Lấy theo tập hợp các chiều [[h,h,..],[c,c,...]]

array([10, 55, 50])

In [19]:
a = np.array([1,2,3,4,5,6])
a[a>3] #Lọc các phần từ trong mảng có giá trị lớn hơn 3

array([4, 5, 6])

In [20]:
a[a%2==0] #Lọc phần tử chẵn

array([2, 4, 6])

In [21]:
b1 = np.array([0,10,20,30,40,50])
b1[1:4] #Cắt các phần từ từ index 1->4

array([10, 20, 30])

In [22]:
b1[:3] #Cắt b1 từ 0 đến index = 3

array([ 0, 10, 20])

# Lắt cắt trên mảng 2 chiều.

In [23]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr2d[:2] # Cắt từ dòng đầu đến dòng 2

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr2d[1:,:2] #Cắt từ dòng 1 đến cuối; từ cột đầu đến cột 2

array([[4, 5],
       [7, 8]])

# Mảng String và Boolean

In [36]:
names = np.array(['Bob','Joe','Tom','Bob','Tom','Joe','Joe'])
names

array(['Bob', 'Joe', 'Tom', 'Bob', 'Tom', 'Joe', 'Joe'], dtype='<U3')

In [37]:
names == 'Bob' #Kiểm tra các phần từ có giá trị bằng  'Bob'

array([ True, False, False,  True, False, False, False])

In [38]:
names[names=='Bob'] # Lọc các phần tử có giá trị bằng  'Bob'

array(['Bob', 'Bob'], dtype='<U3')

In [40]:
arr = np.empty((8,4)) # Tạo mảng 8x4


array([[1.  , 0.  , 0.16, 1.  ],
       [1.  , 0.  , 0.  , 1.  ],
       [1.  , 1.  , 0.  , 1.  ],
       [0.  , 1.  , 0.  , 1.  ],
       [0.  , 1.  , 1.  , 1.  ],
       [0.  , 0.  , 1.  , 1.  ],
       [1.  , 0.  , 1.  , 1.  ],
       [1.  , 0.  , 0.75, 1.  ]])

In [42]:
for i in range(8): # Gán giá trị cho mảng bằng các chỉ số hàng.
  arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [43]:
arr[[4,3,0,6]] #Tách các hàng 4,3,0,6, đi từ trên xuống

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [44]:
arr[[-3,-5,-7]] #Tách các hàng -3,-5,-7 đi từ cuối lên.

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [45]:
arr2 = np.arange(20)

In [51]:
arrMask = (arr2%5==0)
arrMask

array([ True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False])

In [52]:
#Dùng Mask lọc trên arr2
arr2[arrMask] #Lọc ra các phần tử ở vị trí True trong Mask

array([ 0,  5, 10, 15])

In [49]:
arr2>10

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [54]:
arrMask2 = (arr2>=10)
arr2[arrMask & arrMask2] # Kết hợp điều kiện lọc theo Mask và Mask2

array([10, 15])