<a href="https://colab.research.google.com/github/thanh-huy/SIC_Excercies/blob/main/Exam0102.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Thao tác trên Numpy array
## 1.1. Toán tử '+' và '*'

In [1]:
import numpy as np

In [5]:
a = [1,2,3]
type(a)

list

In [3]:
a+a

[1, 2, 3, 1, 2, 3]

In [4]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [6]:
b = np.array(a)

In [7]:
b*3

array([3, 6, 9])

In [8]:
b+b

array([2, 4, 6])

In [9]:
np.repeat(b,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

## 1.1. Toán tử '+' và '*' của Numpy Array

In [17]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [18]:
a+b

array([5, 7, 9])

In [19]:
a-b

array([-3, -3, -3])

In [20]:
a*b

array([ 4, 10, 18])

In [21]:
1.0*a/b

array([0.25, 0.4 , 0.5 ])

## 1.3. Các hàm phổ biến (Universal Functions)

In [22]:
x = np.arange(6) # Tạo 1 mảng gồm các phần tử từ 0 -  5

array([0, 1, 2, 3, 4, 5])

In [23]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [24]:
np.exp(x)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [25]:
type(np.sqrt)

numpy.ufunc

In [26]:
type(np.exp)

numpy.ufunc

## 1.4. Các hàm trên numpy

In [27]:
np.random.seed(123)
a = np.random.randint(1,11, size=1000)

In [28]:
a

array([ 3,  3,  7,  2,  4, 10,  7,  2,  1,  2, 10,  1,  1, 10,  4,  5,  1,
        1,  5,  2,  8,  4,  3,  5,  8,  3,  5,  9,  1,  8, 10,  4,  5,  7,
        2,  6,  7,  3,  2,  9,  4,  6,  1,  3,  7,  3,  5,  5,  7,  4,  1,
        7,  5,  8,  7,  8,  2,  6,  8, 10,  3,  5,  9,  2,  3,  2,  2,  4,
        6, 10,  1,  9,  2,  7,  4,  4,  6, 10,  8, 10,  3,  4,  4,  4,  9,
        7, 10,  8,  7,  4, 10,  7,  7,  7,  2,  4,  5,  4,  2,  1,  6,  9,
        7,  9, 10,  2,  1,  4,  2,  4,  5,  8,  7,  2,  5,  4,  4,  8,  7,
        9,  7,  5,  5,  8,  1,  1, 10,  9,  9,  5,  9,  7,  2,  7,  9,  8,
       10,  2,  8,  2,  8, 10,  9,  8,  2,  4,  2,  9,  8,  6,  2,  3,  6,
        3,  3, 10,  4,  3,  7,  8, 10,  2,  4,  9,  4,  8, 10, 10,  4,  4,
        6,  7,  1,  9,  8,  8,  5,  5,  6,  1,  9, 10,  3,  6,  2,  6, 10,
        3,  5,  4,  1,  4,  8,  8,  3,  6,  2,  8,  6, 10,  2,  3,  9,  6,
        1, 10,  4,  4,  4,  2,  8,  7,  4,  2,  8,  3,  7,  6, 10,  9, 10,
        5,  8,  9,  6, 10

In [29]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
np.median(a)

np.float64(5.0)

In [31]:
np.sum(a)

np.int64(5485)

In [32]:
np.round(np.var(a),2)

np.float64(8.19)

In [33]:
np.round(np.mean(a),2)

np.float64(5.48)

In [36]:
np.round(np.std(a),2)

np.float64(2.86)

In [37]:
np.min(a)

np.int64(1)

In [38]:
np.max(a)

np.int64(10)

## 1.5. Các phương thức thống kê của numpy array

In [40]:
x = np.arange(1,11)

In [41]:
x.sum()

np.int64(55)

In [42]:
x.mean()

np.float64(5.5)

In [43]:
x.std()

np.float64(2.8722813232690143)

In [44]:
x.var()

np.float64(8.25)

In [45]:
x.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [46]:
y = np.arange(1,10)
y = y.reshape((3,-1))
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
print(y.mean(axis=0))
print(y.mean(axis=1))

[4. 5. 6.]
[2. 5. 8.]


In [51]:
z = np.random.randint(10, size=1000)
z

array([6, 9, 9, 5, 6, 9, 5, 3, 4, 5, 4, 0, 8, 0, 4, 6, 2, 4, 1, 9, 2, 9,
       7, 1, 4, 5, 2, 5, 1, 8, 0, 7, 9, 6, 7, 0, 2, 3, 3, 1, 4, 1, 4, 0,
       4, 8, 6, 8, 3, 9, 0, 3, 3, 1, 6, 1, 0, 7, 3, 1, 6, 1, 4, 5, 5, 1,
       0, 1, 8, 9, 5, 3, 4, 1, 6, 2, 1, 0, 6, 9, 5, 2, 7, 6, 3, 6, 7, 6,
       1, 2, 5, 1, 0, 2, 2, 4, 1, 6, 8, 7, 9, 0, 8, 4, 1, 2, 7, 9, 7, 4,
       8, 2, 0, 0, 2, 0, 9, 7, 4, 9, 0, 1, 0, 8, 2, 2, 4, 9, 7, 3, 8, 0,
       8, 0, 5, 3, 3, 2, 0, 3, 0, 1, 6, 9, 2, 1, 8, 4, 4, 3, 3, 8, 2, 9,
       2, 4, 8, 5, 9, 2, 6, 2, 3, 7, 6, 6, 2, 7, 5, 7, 3, 6, 2, 4, 3, 2,
       6, 9, 1, 7, 9, 9, 6, 6, 4, 8, 0, 7, 9, 6, 1, 5, 1, 8, 8, 3, 8, 2,
       1, 2, 2, 0, 5, 8, 6, 7, 5, 5, 4, 8, 2, 8, 4, 2, 7, 8, 8, 6, 6, 5,
       1, 8, 3, 2, 3, 8, 8, 0, 9, 4, 3, 7, 3, 2, 5, 2, 4, 8, 6, 8, 3, 8,
       2, 0, 9, 8, 2, 2, 2, 5, 1, 1, 5, 8, 3, 1, 6, 6, 1, 1, 4, 3, 5, 5,
       8, 8, 4, 0, 7, 1, 6, 2, 4, 2, 6, 4, 5, 6, 5, 7, 0, 3, 6, 4, 8, 8,
       7, 6, 1, 6, 9, 3, 8, 2, 9, 2, 6, 4, 0, 9, 9,

In [52]:
z.max()

np.int64(9)

In [53]:
z.min()

np.int64(0)

In [54]:
(x>5).sum() #Tính tổng có điều kiện

np.int64(5)

In [57]:
sorted(set(z))

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)]

In [59]:
a = np.array([2,-3,4,5,7,0,1,-1])

In [60]:
a.argmax()

np.int64(4)

In [62]:
a.argmin()

np.int64(1)