<a href="https://colab.research.google.com/github/thanh-huy/SIC_Excercies/blob/main/Exam0103.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Các phép toán trên Ma trận

In [1]:
import numpy as np

In [4]:
arr = np.random.randn(6,3) # Khởi tạo ma trận 6x3 ngẫu nhiên
arr

array([[ 1.39677461, -0.86199765,  1.28690457],
       [ 1.05437293,  0.07165099,  1.2299771 ],
       [-0.13630199, -1.35750529,  0.13149788],
       [ 0.34543554, -0.04891206, -1.58224356],
       [-2.08763624,  1.15962987, -1.62939287],
       [-0.53393186, -0.48370504,  0.09956749]])

In [5]:
arr.T #Chuyển vị của ma trận A

array([[ 1.39677461,  1.05437293, -0.13630199,  0.34543554, -2.08763624,
        -0.53393186],
       [-0.86199765,  0.07165099, -1.35750529, -0.04891206,  1.15962987,
        -0.48370504],
       [ 1.28690457,  1.2299771 ,  0.13149788, -1.58224356, -1.62939287,
         0.09956749]])

In [6]:
#Nhân ma trận không sử dụng toán tử *
#Sử dụng np.dot(A,B)
np.dot(arr.T,arr)

array([[ 7.84389383, -3.12295466,  5.87830095],
       [-3.12295466,  4.1720988 , -3.05995184],
       [ 5.87830095, -3.05995184,  8.35458822]])

In [7]:
arr1 = np.arange(12).reshape(3,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
arr1.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
arr1.transpose(0,1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
arr1.transpose(1,0)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [11]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [12]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [13]:
arr.transpose(0,1,2)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [14]:
arr.transpose(2,1,0)

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

# Dùng hàm hoán đổi trục bằng swapaxes

In [15]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [16]:
arr.swapaxes(0,1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])