<a href="https://colab.research.google.com/github/thanh-huy/SIC_Excercies/blob/main/Tensorfllow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import tensorflow as tf
import numpy as np

In [5]:
tf.__version__

'2.20.0'

In [18]:
a = np.array([1,2,3],dtype=np.int32)
b = [4,5,6]
t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)
print(t_a)
print(t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [10]:
tf.is_tensor(t_a), tf.is_tensor(a)

(True, False)

In [11]:
t_ones = tf.ones((2,3))
t_ones.shape

TensorShape([2, 3])

In [12]:
t_ones.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [13]:
const_tensor = tf.constant([1.2,5,np.pi], dtype=tf.float32)
print(const_tensor)

tf.Tensor([1.2       5.        3.1415927], shape=(3,), dtype=float32)


In [14]:
tf.fill((2,3),1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [16]:
tf.one_hot([0,1,1,2],4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]], dtype=float32)>

In [20]:
t_a_new = tf.cast(t_a, tf.int64)
print(t_a_new.dtype)

<dtype: 'int64'>


In [22]:
t = tf.random.uniform(shape=(3,5))
t_trans = tf.transpose(t)
print(t.shape,'-->', t_trans.shape)

(3, 5) --> (5, 3)


In [25]:
t = tf.zeros((30,))
t_reshape = tf.reshape(t,shape=(5,6))
print(t.shape,'-->', t_reshape.shape)

(30,) --> (5, 6)
